[tool.poetry]
name = "mielib"
version = "0.1.4"
description = ""
authors = ["Ivan Toftul <toftul.ivan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
